markdown: rdiscount
permalink: /:title/
url: http://github.shanechu.com
highlighter: pygments
title: shane的随想录
name: shane的随想录
email: enginzhu@gmail.com
description: 在群体里容易按照他人的想法生活，在孤独中容易按照自己的想法生活。但值得记住的只是那些在群体中保持独立的人。
author: shanechu
duoshuo: shanechu
weibo: 1716213977
hub: enginzhu
safe: true
paginate: 100
